# Introducción: 

<div style="text-align: justify">

Los altos niveles de desigualdad socioeconómica, su aumento en varios países alrededor del mundo y sus consecuencias, son fenómenos que han generado preocupación tanto entre cientistas sociales como en el espacio público [@Mijs2019; @roex_attitudes_2019; @seery_working_2014; @worldeconomicforum_global_2014]. El debate sobre la desigualdad social en Chile no es nuevo y ha sido relevado en vista de diversos acontecimientos recientes, como lo es el estallido social del 2019. Se ha considerado que la desigualdad social posee diferentes dimensiones, siendo algunas de ellas la normativa, funcional y las percepciones sobre justicia -e injusticia- [@PNUD2017]. Gran parte de la investigación sociológica sobre desigualdad social se ha enfocado en estratificación social y movilidad social, en parte por contar con medidores objetivos que se presentan como concretas de la experiencia de la desigualdad. Por otra parte -y complementario al campo de estudios mencionado-, existe la línea de investigación sobre las desigualdades subjetivas, centrándose en las creencias y explicaciones de la desigualdad social, así como también sobre los principios que organizan estas, sus determinantes y consecuencias [@Iturra2019]. Dentro del tema de las desigualdades subjetivas, surge un problema de relevancia, sobre todo en sociedades altamente desiguales como lo es la chilena, siendo este los mecanismos y explicaciones que justifican las desigualdades sociales.

Una variable que ha sido relacionada a las justificaciones de desigualdades sociales son las atribuciones de pobreza y riqueza -de manera resumida, el cómo la gente se explica las carencias o grandes ventajas de grupos sociales- [@Frei2020a]. Tradicionalmente se han categorizado en internas y externas, en donde las primeras responsabilizan a las personas por su situación -por ejemplo, explicar la pobreza como consecuencia de la falta de esfuerzo-, mientras que las segundas son explicaciones en que se responsabiliza a la sociedad -por ejemplo, explicar la pobreza como consecuencia de la falta de oportunidades- [@pontificiauniversidadcatolicadechile_dimensiones_2018]. La investigación ha relacionado las atribuciones internas con la justificación de desigualdades, percepciones en general sobre desigualdades, actitudes hacia ricos y pobres [@pontificiauniversidadcatolicadechile_dimensiones_2018] y aversión hacia políticas redistributivas [@sainz_where_2019]. De aquí surge una primera interrogante, la cual es ¿Qué explica las diferencias entre individuos en atribuciones de pobreza y riqueza?

La evidencia empírica incluye diversas variables para explicar las diferencias entre atribuciones internas y externas. Por un lado, están las variables contextuales, usándose tradicionalmente el criterio de nacionalidad, como en el trabajo de @bucca_merit_2016. Por otro lado, están las variables individuales, destacandose en sociología las variables sociodemográficas -como la edad o el sexo- y de estratificación social -como la ocupación, escolarización, ingresos, entre otros-. Pero, además, las atribuciones -de carácter interno- han sido relacionadas con las creencias meritocráticas [@bucca_merit_2016; @madeira_primes_2019; @major_ideology_2017].

La meritocracia puede entenderse como un sistema de distribución de recursos y recompensas basado en el mérito individual, siendo en su concepción original una combinación de talento y esfuerzo [@young_rise_1962]. En general, la agenda investigativa en sociología y psicología social sobre meritocracia -la cual aún se encuentra poco consolidada- ha trabajado con las creencias meritocráticas, asociándose esta a su vez con otras variables como la legitimación de desigualdades socioeconómicas [@castillo_measuring_2020]. 

Si bien las atribuciones de carácter interno se han relacionado con la legitimación de las desigualdades basado en el principio de la justicia meritocrática -es decir, quien se esfuerza más y tiene mayor talento recibe más- [@frei_fruto_2020], muchas veces se da por sentada la relación entre meritocracia y atribuciones internas sin un trabajo empírico previo -como por ejemplo, en la investigación de @bucca_merit_2016-. Aunque la evidencia preliminar sugiere que aquellos que muestran mayor afinidad por las creencias meritocráticas tienden a atribuir la pobreza -y la riqueza- a factores más internos que externos, es necesario ahondar en la relación entre meritocracia y atribuciones de pobreza y riqueza de manera empírica. Para ello, se plantea la siguiente pregunta que guiará la investigación: ¿Cómo se relacionan las creencias meritocráticas con las atribuciones de pobreza y riqueza? 

## La sostenida desigualdad socioeconómica en Chile.

<div style="text-align: justify">

Chile suele ser comparado con sus países vecinos debido al crecimiento económico que logró luego de la crisis económica de los ochenta. Esto ha sido acompañado por un mejoramiento infraestructural, educacional, de servicios sociales y de incremento de salarios [@pnud_desiguales_2017]. Además, la pobreza se redujo enormemente, en donde en 1990 aproximadamente un 70% de las personas vivían bajo la línea de la pobreza, reduciéndose a un 8,6% en 2017 [@ministeriodedesarrollosocial_evolucion_2017]. 

Esto se inserta en el contexto post-dictatorial de los años noventa, en donde se termina de afianzar el modelo económico de liberalización económica y financiera impuesto en dictadura, y en el cual se siguieron impulsando reformas en esta línea [@araujo_sujeto_2017]. En este proceso se genera un reordenamiento institucional y un rediseño de las fronteras entre mercado y Estado [@araujo_sujeto_2017]. La adopción de nuevas dinámicas socioeconómicas permitió el mantenimiento de desigualdades socioeconómicas históricas del país [@pnud_desiguales_2017] y que aumentase la segregación tanto de espacios urbanos, como de prestaciones de servicio básicos [@pnud_desiguales_2017]. 

Además del mantenimiento de los niveles históricos de desigualdad, Chile se encuentra entre los países más desiguales de América Latina y los países desarrollados [@flores_top_2019]. En comparación con países de la OCDE, para el año 2015 Chile presentaba un Gini del 48%, mientras que todos los países de la OCDE marcaron por debajo del 35% [@pnud_desiguales_2017]. Un aspecto fundamental de la desigualdad en Chile es la concentración de riquezas en el 1% más rico, lo cual se refleja en debates como el de los impuestos a los super ricos [@lopez_hiper_2020]

## Cambios culturales y de subjetividades en la sociedad chilena

<div style="text-align: justify">

La introducción de la flexibilización, las lógicas de competencia y el quiebre de asociatividad en el mercado de trabajo, junto a la adopción de una cultura del crédito, son algunos de los factores que gatillaron un gran cambio tanto en la vida social junto a sus relaciones, como también sobre las subjetividades de la población [@araujo_sujeto_2017; @espinoza_que_2008].

Con la expansión en la oferta de bienes y servicios, un aumento en el consumo y el acceso masivo por parte de la población a la educación terciaria, se masifica la idea de pertenencia a una clase media [@frei_fruto_2020]. En este sentido, los grupos sociales de pobres y ricos comienzan a percibirse como más extremos. Además, la mayoría de la población se percibe en una mejor posición económica respecto a la generación de sus padres [@pnud_desiguales_2017] lo cual influye en la evaluación de las propias trayectorias y de autoposicionamiento, atribuyendo gran parte de esta movilidad social al esfuerzo propio y familiar [@guzman_legitimacion_2017]. 

Estas transformaciones abren un escenario complejo, en el cual los individuos se relacionan de manera ambigua y a veces contradictoria con los cambios que se irán produciendo [@araujo_sujeto_2017]. Ello se observa en que se irá gestando una opinión crítica generalizada hacia el modelo [@araujo_sujeto_2017] como también una percepción de mayor desigualdad socioeconómica [@pnud_desiguales_2017]. Pero existe otra arista, en donde se observa cierto apego hacia lo que han traído estas transformaciones [@araujo_sujeto_2017].

El mérito, como valor y mecanismo generador de juicios [@araujo_sujeto_2017] se instala con fuerza en la sociedad chilena a partir de los años noventa. Los estudios que trabajan el mérito suelen destacar una dimensión contradictoria y en ocasiones conflictiva del concepto. Contradictoria en el sentido de que, por un lado, es un concepto crítico en cuanto el mérito se opone a la distribución de bienes y oportunidades mediante las estructuras económicas clásicas -como por ejemplo la distribución de bienes a través de la herencia y títulos adscriptivos-, planteándose como una idea democratizadora sobre las distribuciones de recursos. Por otro lado, se evidencia que el discurso meritocrático posee un carácter estigmatizador sobre grupos desaventajados, reflejándose, por ejemplo, en la idea de que estos grupos no surgen por su falta de iniciativa o esfuerzo [@pnud_desiguales_2017]. En este sentido vendría a cumplir un rol en la legitimación de desigualdades socioeconómicas [@castillo_meritocracia_2019]. 

Considerando lo expuesto en cuanto a la dimensión más crítica y con afanes democratizadores en el concepto de mérito, el adherir a  creencias meritocráticas se posiciona como una opción válida y justa a la hora de ordenar de forma jerárquica a la sociedad. @cocina_cinco_2013 señala que “Con más o menos convicción, todos creemos en la meritocracia. Todos creemos que debiese haber igualdad de oportunidades” (s.p.). De esta manera, el mérito como principio distributivo se introduce en esferas como la política, la sociedad civil y la academia. 

En el área de las ciencias sociales, surgen estudios bajo la lógica de la justicia de mercado, la cual sostiene que la posición que ocupan los individuos en la jerarquía social es producto de sus esfuerzos y méritos [@lane_market_1986]. Diversas investigaciones se enmarcan en esta idea de que para combatir la desigualdad socioeconómica se deben mejorar los mecanismos meritocráticos y de igualdad de oportunidades. Sin embargo, las creencias meritocráticas no se oponen a la desigualdad, sino más bien a la discriminación [@mijs_meritocracy_2020]. El argumento central de este estudio va en línea con lo último señalado y discute con la idea de la meritocracia como un sistema distributivo justo, al plantear la hipótesis principal de que las percepciones meritocráticas influyen de manera positiva en las atribuciones de carácter interno, siendo estas últimas un elemento clave en la legitimación de desigualdades socioeconómicas.

## Objetivos de investigación

<div style="text-align: justify">

Para responder a la pregunta de ¿Cómo se relacionan las creencias meritocráticas con las atribuciones de pobreza y riqueza?, se propone el objetivo doble de, por un lado, **(1)** analizar la relación entre atribuciones de pobreza y riqueza con las creencias meritocráticas, y por otro lado, **(2)** analizar los cambios en la relación entre atribuciones de pobreza y riqueza con las creencias meritocráticas para los años 2000, 2009 y 2019.

## Estructura de investigación

<div style="text-align: justify">

El **capítulo 2**: Atribuciones de pobreza y riqueza, es una revisión anaítica y empírica sobre la conceptualización de las atribuciones de pobreza y riqueza, en donde, además, se discute las formas de medición y operacionalización de la variable en estudios cuantitativos. Al final del capítulo se señalan los principales estudios y antecedentes sobre las atribuciones de pobreza y riqueza. 

El **capítulo 3**: Meritocracia, constituye una segunda sección de análisis conceptual, en donde se revisan antecedentes y se define conceptualmente la meritocracia. Posteriormente en el mismo capítulo, se revisa el concepto de creencias meritocráticas y cómo este se construye, esto es, a partir de las percepciones y las preferencias meritocráticas. Finalmente, se introduce la discusión sobre la relación entre meritocracia y las atribuciones de pobreza y riqueza, para luego proceder a la presentación de hipótesis. 

El **capítulo 4**: Metodología, presenta los datos y variables utilizados. Además se señala los métodos a utilizar.

El **capítulo 5**: Resultados.

El **capítulo 6**: Discusiones.

