
```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

# Antecedentes

## Atribuciones de pobreza y riqueza

### Conceptualización y medición de atribuciones

<div style="text-align: justify">

Desde la tradición de investigación cuantitativa, el estudio sobre atribuciones se ha focalizado en tres constructos principales desarrollados por @feagin_subordinating_1975: (a) explicaciones individuales que atribuyen la pobreza y la riqueza a factores individuales como la irresponsabilidad personal y la falta de esfuerzo, capacidad o talento; (b) explicaciones estructurales que atribuyen la pobreza y la riqueza a factores estructurales como los bajos salarios, la discriminación y la mala calidad de la educación; y (c) explicaciones fatalistas que atribuyen la pobreza y riqueza a la mala suerte, enfermedad y circunstancias desafortunadas [@godfrey_developing_2016]. No obstante, la tercera ha presentado menor consistencia [@bullock_predicting_2003]. En este sentido, las atribuciones suelen estudiarse de manera dicotómica entre atribuciones internas y externas [@heider_psychology_1958; @kluegel_beliefs_1986]. En resumen, las atribuciones internas enfatizan la disposición personal, mientras que las externas atribuyen la culpa al entorno social por las desigualdades socioeconómicas en la sociedad [@schneider_poverty_2015]. 

Las atribuciones internas han sido relacionadas con la legitimación de las desigualdades sociales basado en la agencia individual. Por otra parte, la dimensión externa entrega explicaciones desde la discriminación o causas estructuralistas, a lo que se asocia una visión más crítica acerca de la distribución en la sociedad y las desigualdades. Es importante señalar que las atribuciones internas y externas no siempre se comportan de manera opuesta, como si fuesen parte de un continuo unidimensional. Las atribuciones pueden ser una combinación de explicaciones internas y externas [@bucca_merit_2016; @osborne_latent_2015] y/o favorecer cierta interpretación para grupos pobres y otra para grupos ricos [@hunt_race_2004]. 

Se ha descrito que, en sociedades altamente desiguales, los mecanismos subjetivos de la población para explicar las desigualdades, la pobreza y riqueza son predominantemente de carácter individualistas. En este sentido, la agencia individual cobra gran relevancia como factor explicativo. Llevado al caso chileno, se ha observado un cambio en las atribuciones de la pobreza y riqueza a partir de la década de los noventa hasta el 2015 en la dirección de explicaciones individualistas -atribuciones internas-, aunque con una fuerte dimensión ambivalente o combinada entre explicaciones internas y externas [@frei_fruto_2020]. 

La mayor parte de las investigaciones sobre atribuciones se centran en el estudio de las atribuciones de pobreza [@cozzarelli_attitudes_2001; @schneider_poverty_2015], aunque también se trabaja conjuntamente las atribuciones de pobreza y riqueza [@bucca_merit_2016; @frei_fruto_2020; @kreidl_perceptions_2000]. Un problema recurrente en el estudio de las atribuciones de pobreza y riqueza es el de llegar a conclusiones para ambos fenómenos sin un tratamiento empírico previo. Considerando que “(...) las atribuciones internas de la pobreza se asocian a atribuciones internas de la riqueza, ocurriendo lo mismo para las atribuciones externas” [@pontificiauniversidadcatolicadechile_dimensiones_2018, pag. 8], es posible y recomendable trabajar conjuntamente ambos fenómenos. En este sentido, el incluir tanto atribuciones de pobreza como atribuciones de riqueza, sirve justamente para enriquecer el estudio sobre atribuciones y generar un análisis e interpretaciones comparativas para ambos fenómenos. 

Otro de los problemas que se presentan a la hora de estudiar las atribuciones, es que los datos disponibles son escasos, sobre todo al considerar el conjunto de atribuciones de pobreza y riqueza [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Pero además está el problema de medición, en donde, si bien algunos indicadores coinciden en distintas encuestas, no existe un consenso general sobre una escala común [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Esto genera problemas al momento de comparar estudios. 

Tradicionalmente existen dos formas comunes de incorporar las atribuciones en las encuestas. En una se presentan las distintas razones que explican las carencias o grandes ventajas de las personas, junto a una escala de frecuencia o de acuerdo/desacuerdo. En la otra, se presenta una lista de razones que explican las carencias o comodidad de las personas, en la cual debe seleccionarse una o dos -dependiendo del caso-. En el presente estudio las variables de atribuciones corresponden a este último método de medición.


### Antecedentes de las atribuciones de pobreza y riqueza

#### Consecuencias de las atribuciones de pobreza y riqueza

<div style="text-align: justify">

Las atribuciones de pobreza y riqueza han sido relacionadas con distintos fenómenos sociales, como la percepción y justificación de desigualdades sociales y económicas [@lepianka_popular_2010; @oorschot_blame_2000; @schneider_poverty_2015], el apoyo a políticas redistributivas [@alesina_fighting_2004; @alesina_preferences_2009; @andersen_social_2015; @benabou_social_2001; @bullock_predicting_2003; @sainz_less_2020], actitudes hacia los pobres [@cozzarelli_attitudes_2001], entre otros. 

Las principales conclusiones sobre los efectos de las atribuciones de pobreza y riqueza en los distintos fenómenos sociales mencionados anteriormente son que las atribuciones internas justifican las desigualdades socioeconómicas, mientras que las externas las desafían [@schneider_poverty_2015]; mantener atribuciones internas reduce el apoyo a intervenciones gubernamentales y políticas redistributivas, mientras que las externas aumentan el apoyo [@bullock_predicting_2003]; y por último, que las atribuciones internas favorecen actitudes negativas hacia los pobres, mientras que las atribuciones externas afectan de manera positiva a las actitudes y estereotipos de los pobres [@cozzarelli_attitudes_2001].

Adicional a la evidencia presentada, es importante destacar algunos avances recientes desde la psicología social, en donde las atribuciones sobre las causas de la pobreza y riqueza se han relacionado al concepto de deshumanización [@sainz_less_2020]. La deshumanización se entiende como procesos y circunstancias que niegan aspectos humanos en grupos sociales, los cuales tienen consecuencias de discriminación y de prejuicios degradantes [@dixon_prejudice_2012; @pereira_infrahumanization_2009], como también de legitimación de diferentes tipos de desigualdades [@sainz_less_2020]. Se ha señalado que la deshumanización tiene efectos estigmatizantes hacia grupos de estatus socioeconómico bajo, como, por ejemplo, contribuyendo a la percepción de que la pobreza es un estado estable y permanente que no puede resolverse mejorando las condiciones socioeconómicas de las familias pobres [@sainz_less_2020]. En síntesis, estos estudios recalcan la necesidad de estudiar las atribuciones de pobreza y riqueza, en vista de que se han relacionado con la legitimación de las desigualdades y con una demanda más baja por políticas redistributivas [@sainz_where_2019]. 

#### Causas en las atribuciones de pobreza y riqueza

<div style="text-align: justify">

Además de la relación entre las atribuciones de pobreza y riqueza con los diversos temas mencionados en el apartado anterior, existen investigaciones que ahondan en las causas de mantener atribuciones internas, externas o mixtas. Es posible dividir estas variables en tres grupos, los cuales son las variables de carácter contextual, y las de nivel individual, que a su vez pueden separarse en variables de carácter objetivo o estructural y subjetivas. Las variables contextuales suelen usarse en investigaciones de comparación internacional, por lo que no se ahondará en ellas y se dará prioridad a las variables de nivel individual. 

Dentro de las variables objetivas, las variables sociodemográficas son comunes a casi todas las investigaciones de atribuciones y actitudes hacia la pobreza. @kluegel_beliefs_1986 nos entregan una aproximación temprana sobre la relación entre variables sociodemográficas, como son la edad, sexo, orientación política e ingreso y variables de creencias sobre la pobreza. Se afirma que, al menos en el caso de Estados Unidos, todas presentan una correlación débil, a excepción de la variable de raza. En este sentido, quienes se identifican como afroamericanos son algo menos propensos que los blancos a enfatizar factores individualistas [@kluegel_beliefs_1986]. Una reflexión importante en este estudio es que la baja correlación de estas variables podría atribuirse a la influencia generalizada de la ideología del individualismo.

En cuanto a la relación entre variables sociodemográficas y atribuciones de pobreza y riqueza para el caso chileno, la investigación de @frei_fruto_2020 nos muestra que tanto sexo como orientación política no producen diferencias en las atribuciones. No obstante, respecto a la variable edad se observa que los grupos de mayor edad tienen mayor probabilidad de observar atribuciones internas.

Dentro de la tradición sociológica, las variables de estratificación social son centrales a la hora de analizar fenómenos sociales. Para el caso de las atribuciones y actitudes hacia la pobreza, los resultados de distintas investigaciones son variados y en ocasiones contradictorias. Ciertos hallazgos se agrupan en la llamada “underdog thesis” (tesis de los desvalidos/desvalorizados), la cual plantea que personas de estatus socioeconómicos altos tienden a percibir causas individualistas en las atribuciones de pobreza, mientras que grupos de estatus bajo mantendrían creencias de carácter más estructuralistas (externas) [@hunt_race_2004; @robinson_equality_1978]. Una posible explicación sería que los grupos sociales aventajados tienen intereses en mantener sus ventajas a través de la autojustificación, mientras que los grupos bajos generarían una visión crítica respecto de su propia situación [@kluegel_beliefs_1986; @mijs_paradox_2019]. 

Contrario a la underdog thesis, se ha planteado que las personas de estatus socioeconómico más bajo mantienen percepciones y creencias de carácter interno -individualista-. Esto podría explicarse, en parte, debido a que personas en situación de pobreza a menudo subestiman el alcance de su pobreza y desventaja relativa, y pueden culparse a sí mismas de sus circunstancias (atribuciones internas) [@mijs_paradox_2019].

Para el caso chileno se observa que quienes pertenecen a quintiles más bajos atribuyen más causas internas a la pobreza y riqueza, aunque con la educación pasa lo contrario -a mayor educación, más causas internas- [@frei_fruto_2020]. Estos resultados rechazan en parte la hipótesis ilustrada, la cual plantea que a mayor nivel educacional se entregan más atribuciones de carácter externo. Dichos resultados podrían relacionarse con un mecanismo de autolegitimación de sectores más altos [@frei_fruto_2020]. Sin embargo, la interpretación de la relación entre educación y atribuciones de pobreza y riqueza carece de consistencia debido a la forma en que se mide las variables.

Además de la relación entre las variables objetivas y/o estructurales anteriormente mencionadas, destacan las variables subjetivas como determinantes en las atribuciones de pobreza y riqueza. Dentro de estas son centrales las variables sobre creencias de estratificación [@kluegel_beliefs_1986], sobre experiencia personal en diferentes aspectos -como exposición a la pobreza y experiencia de movilidad social- [@lepianka_popular_2010] y valores e ideología [@lepianka_popular_2010; @madeira_primes_2019]. 

La síntesis de los principales antecedentes de la investigación de @lepianka_are_2007 pueden ayudar como guía de algunas de las principales variables subjetivas utilizadas. Las variables causales se agrupan en cinco categorías: conciencia de la existencia de pobreza, experiencia personal de desventaja, valores y creencias, características sociodemográficas y características contextuales (nacionales). Cabe destacar que la forma de medición en esta investigación corresponde a una lista de cinco posibles opciones para responder a la pregunta sobre causas de la pobreza, en donde se debe elegir la primera y segunda causa más importante.

Los principales resultados de la investigación anterior son que las creencias de justicia distributiva son importantes para las atribuciones de pobreza causal. Aquellos que se adhieren más firmemente al igualitarismo o al principio de necesidad tienen más probabilidades de atribuir la pobreza al mal funcionamiento del sistema distributivo, y menos probabilidades de ver la pobreza como causada internamente. Por otra parte, el respaldo al principio de mérito se relaciona directamente con la atribución interna. Cabe destacar que estos resultados hacen referencia únicamente a las atribuciones de pobreza, y para el caso de las atribuciones internas se utiliza la variable de la explicación de la pobreza como causa de la pereza.

En la siguiente sección se profundizará en el concepto de las creencias meritocráticas, variable perteneciente al conjunto de las variables subjetivas, para luego indagar en cómo esta puede estar relacionada a las atribuciones de pobreza y riqueza.

## Meritocracia

### Un concepto controversial

<div style="text-align: justify">

El concepto de meritocracia, a partir de su aparición en la obra satírica y crítica de @young_rise_1962, ha crecido en popularidad, apareciendo en diferentes espacios de la cotidianidad. De la mano con dicha popularidad, el concepto ha sido objeto de diversas interpretaciones. Esto es algo que ha sido identificado hace ya algún tiempo, siendo reconocida la meritocracia por @sen_merit_2000 como un concepto de poca claridad. El no tratar detalladamente el concepto de meritocracia, puede presentar problemas que obstaculicen la investigación empírica y la posterior comparación entre estudios. Es posible entender a la meritocracia como un orden social que basa la distribución de los recursos a partir del mérito individual. A su vez, el mérito opera a partir de los criterios de esfuerzo y talento [@young_rise_1962]. 

Es común encontrar en discursos de autoridades y en la cultura y entretenimiento la promoción de la meritocracia, en el sentido de que cualquiera que sea la posición social de un sujeto al nacer, la sociedad debería ofrecer suficientes oportunidades y movilidad para que el "talento" se combine con el "esfuerzo" para "llegar a la cima" [@littler_meritocracy_2017]. Así, desde presidentes de diferentes países [@littler_meritocracy_2017] hasta autoridades locales como políticos chilenos de distintos sectores [@cocina_cinco_2013], la meritocracia se ha convertido en la gran promesa para transformar a la sociedad en una más justa y democrática. 

El incrementar la movilidad social y promover la igualdad de oportunidades como propuestas meritocráticas se enmarca en la agenda política liberal igualitaria, a partir de la cual proliferaron investigaciones enfatizando que los principios meritocráticos no se aplican de manera correcta o en justa medida [@mijs_meritocracy_2020]. Desde este enfoque, el problema no sería la desigualdad misma si no los mecanismos que la legitiman. Tal como menciona [@mijs_paradox_2019], la meritocracia no se opone a la inequidad sino más bien a la discriminación -y otros mecanismos de distribución no meritocráticos-.

El hecho de que la meritocracia sea un mecanismo inservible para combatir la desigualdad socioeconómica ha guiado estudios preocupados por las consecuencias de las creencias meritocráticas. Algunas investigaciones con enfoque crítico argumentan que, a mayor creencia meritocrática, más se legitiman las desigualdades [@castillo_measuring_2020; @madeira_primes_2019]. @madeira_primes_2019 argumentan que la prominencia de las creencias meritocráticas facilita el uso de atribuciones causales internas, evaluaciones negativas y estereotipos hacia grupos de bajo estatus, lo cual al mismo tiempo afecta negativamente las decisiones que involucran a miembros de grupos de bajo estatus, particularmente en contextos organizacionales. 

Además, han surgido críticas a la idea de meritocracia como un principio distributivo justo, en cuanto respalda un sistema competitivo, lineal y jerárquico en el que, por definición, ciertas personas deben quedar atrás [@littler_meritocracy_2017]. Por otra parte, se ha argumentado que la igualdad de oportunidades como idea fuerza de la meritocracia, no implica necesariamente que una sociedad sea más justa [@cocina_cree_2013]. En este sentido, podría considerarse más bien como una condición necesaria pero no suficiente para que un orden social sea justo [@cocina_cree_2013].

### Las creencias meritocráticas en las ciencias sociales

<div style="text-align: justify">

La investigación empírica de las creencias sobre estratificación social distingue entre la dimensión objetiva y subjetiva [@kluegel_beliefs_1986]. La primera constituye una tradición sociológica de amplio repertorio, abarcando medidas objetivas para estudiar el posicionamiento de los individuos en la sociedad, como lo son el ámbito ocupacional, educación y movilidad social [@ganzeboom_comparative_1991; @goldthorpe_myth_2003]. Por otra parte, en cuanto a la dimensión subjetiva de la estratificación social, la desigualdad es un nicho importante de estudios. La presente investigación se enmarca en el área de estudios denominado por @kluegel_beliefs_1986 como desigualdad subjetiva. Esta aglutina diversos temas y metodologías, siendo central el estudio de las creencias meritocráticas, aunque aún sigue siendo un área limitada [@castillo_meritocracia_2019].

Parte de la discusión reciente sobre el concepto de las creencias meritocráticas se ha enfocado en su definición conceptual y su operacionalización. Se ha abordado la confusión que genera el término creencias -beliefs- meritocráticas, en vista de que algunos autores utilizan el concepto como las percepciones que se tienen de los mecanismos meritocráticos que operan en la sociedad, mientras que otros dan más énfasis al aspecto normativo, refiriéndose a cómo debiesen funcionar -preferencias- estos mecanismos [@frei_fruto_2020]. 

La falta de claridad conceptual sobre lo que se entiende por creencias meritocráticas, ha generado el problema de no tener una base empírica para la investigación de la meritocracia. Para facilitar el trabajo empírico en torno al ambiguo término de creencias meritocráticas, surge la propuesta de distinguir entre las percepciones y preferencias meritocráticas [@castillo_meritocracia_2019]. Las percepciones meritocráticas hacen referencia a cómo las personas creen que funcionan los mecanismos meritocráticos en una sociedad en específico, mientras que las preferencias meritocráticas refieren a cómo estos deberían ser y funcionar en la sociedad [@castillo_meritocracia_2019]. Esta conceptualización se enmarca en la perspectiva subjetiva del estudio de la meritocracia, en donde esta última se compone de las perspectivas normativas -preferencias- y las descriptivas -percepciones- [@castillo_meritocracia_2019]. 

Además del problema conceptual sobre percepciones y preferencias meritocráticas, se ha discutido sobre la aplicación de las dos dimensiones que componen a la meritocracia -talento y esfuerzo- en distintas investigaciones [@castillo_measuring_2020]. En algunos casos se trabajan las creencias meritocráticas de manera unidimensional, como por ejemplo en la investigación de [@mijs_paradox_2019], en donde se da mayor énfasis al esfuerzo en el trabajo por sobre el talento. No obstante, se ha comprobado empíricamente que el constructo de meritocracia se compone a partir de la asociación entre talento y esfuerzo [@castillo_measuring_2020], por lo que trabajar con una sola dimensión puede significar sesgos en la investigación.

Por último, algunas investigaciones han incluido elementos no-meritocráticos en la operacionalización de meritocracia, asumiendo una escala continua en donde en un extremo se ubican elementos no-meritocráticos mientras que en el otro extremo elementos meritocráticos [@kunovich_systems_2007; @newman_false_2015]. En este sentido, el rechazo a mecanismos no-meritocráticos, como el tener éxito a partir de la posición aventajada de la familia o a partir de los contactos sociales, implicaría un mayor apoyo a mecanismos meritocráticos. Al ser sometido a escrutinio empírico, se ha establecido que factores no-meritocráticos no están necesariamente relacionados a factores meritocráticos [@castillo_measuring_2020]. De esta manera, es conveniente incluir factores no-meritocráticos en las investigaciones empíricas sobre la meritocracia, pero no reducirlos al mismo continuo, sino trabajando ambos elementos como independientes. La presente investigación tratará específicamente elementos meritocráticos.

### Creencias meritocráticas y atribuciones de pobreza y riqueza

<div style="text-align: justify">

La meritocracia ha sido conceptualizada como un principio de justicia distributiva que permitiría a la gente creer que se vive en una sociedad justa aún en sociedades altamente desiguales [@mijs_paradox_2019]. De esta manera, la meritocracia cumple un rol de legitimación de desigualdades sociales y promotor de una jerarquía social ordenada por grupos sociales en distintos niveles [@castillo_meritocracia_2019]. 

Por su parte, las atribuciones de pobreza y riqueza operan como una expresión de sistemas de valores y creencias, al ser estas explicaciones de las causas de que grupos sociales pertenezcan a un lugar u otro en la jerarquía social. Además, debido a la desigualdad socioeconómica y a los altos niveles de autoidentificación con las clases medias [@espinoza_que_2008], es posible que los grupos sociales explicados se perciban como distintos a la situación propia de la mayoría, e incluso como marginales. 

La investigación sugiere que se culpa cada vez más a los pobres de su desgracia y se elogia los éxitos de los ricos por su mérito personal [@mijs_paradox_2019], y cuanto más alto es el estatus socioeconómico de un individuo, es más probable que atribuya ventajas y desventajas sociales al mérito o culpa personal [@bucca_merit_2016]. 

Sin embargo, en ocasiones se usa indistintamente el concepto de mérito para las atribuciones internas, como es el caso de la investigación “Merit and blame in unequal societies: Explaining Latin Americans’ beliefs about wealth and poverty” de @bucca_merit_2016. Si bien ambas variables pertenecen al mismo área de creencias sobre desigualdades sociales, e incluso algunas atribuciones de pobreza utilizan elementos de las creencias meritocráticas -como la explicación de la pobreza por la flojera y falta de iniciativa, relacionada con el esfuerzo-, no obstante, existen atribuciones internas en donde se responsabiliza al individuo de su situación sin existir una relación clara con el mérito o la meritocracia -por ejemplo, explicar la pobreza por los vicios y el alcoholismo-. 

### Antecedentes en la relación entre meritocracia y atribuciones de pobreza

<div style="text-align: justify">

En la investigación de @lepianka_popular_2010 sobre atribuciones de pobreza, se ve un primer acercamiento a la influencia de la meritocracia sobre las primeras. Las variables del estudio que se relacionan con la meritocracia son (1) “adherencia” al mérito como justo, y (2) la ética del trabajo (PWE por sus siglas en inglés). El mérito como justo se extrae de la pregunta acerca de los elementos que son importantes para que una sociedad sea considerada como justa. A partir de esta pregunta, los encuestados debieron responder el grado de acuerdo o desacuerdo con la frase de “Reconocer a las personas por sus méritos”. Se concluye que a medida que la gente respalda con más fuerza el principio de mérito como justicia, es más probable que se atribuya la pobreza a la pereza antes que a causas estructurales. Por otro lado, respecto a la segunda variable, se concluye que un mayor respaldo a la ética del trabajo (PWE) se relaciona con una mayor propensión a atribuir la pobreza a la ociosidad individual y una menor inclinación a ver la miseria como causada por factores externos, y especialmente la injusticia social.

En una línea similar, se ha estudiado la relación de la meritocracia -bajo la forma de las variables de creencias legitimadoras de estatus (SLB por sus siglas en inglés) y PWE- con actitudes hacia grupos marginados -principalmente a partir de criterios étnicos y de género- [@madeira_primes_2019; @major_ideology_2017]. Se concluye que las creencias meritocráticas cumplen un rol legitimador sobre las desigualdades entre grupos sociales. De manera más específica, se señala que la meritocracia descriptiva -percepciones- está relacionada negativamente con los resultados psicológicos y conductuales intergrupales, mientras que la meritocracia prescriptiva -preferencias- no lo está [@madeira_primes_2019]. De hecho, en el estudio de @madeira_primes_2019, se señala que mayores niveles de preferencia meritocrática tienen un menor efecto en actitudes negativas hacia grupos desfavorables -en este caso hacia las mujeres-, como también que favorecen la aceptación de políticas sociales de defensa del mérito diseñadas para lograr una mayor igualdad intergrupal en el lugar de trabajo (por ejemplo, discriminación positiva) y una mayor oposición a las políticas que violan principios meritocráticos.

A modo de síntesis, la literatura recolectada hasta la fecha sobre creencias meritocráticas y atribuciones de pobreza y riqueza carecen de dos aspectos importantes: trabajar conjuntamente las atribuciones de pobreza y riqueza, y una operacionalización sistemática del concepto de creencias meritocráticas.

Considerando que mayores niveles de percepción meritocrática se ha relacionado con una dimensión legitimadora de las desigualdades socioeconómicas [@castillo_meritocracia_2019] y con actitudes negativas hacia grupos sociales marginalizados [@madeira_primes_2019], se plantea la siguiente hipótesis que responde al primer objetivo de (1) analizar la relación entre atribuciones de pobreza y riqueza con las percepciones meritocráticas:

> $H_1:$ A mayor percepción de meritocracia, mayores serán las atribuciones internas hacia la pobreza y la riqueza.

Respecto al segundo objetivo de (2) analizar los cambios en la relación entre atribuciones de pobreza y riqueza con las percepciones meritocráticas para los años 2000, 2009 y 2019 se considerarán principalmente dos elementos para plantear la hipótesis. En primer lugar, se consideran los resultados de la investigación de Frei y colegas (2019), la cual da cuenta de un aumento en las atribuciones internas y ambivalentes en la sociedad chilena entre 1996 y 2015. En segundo lugar, distintas investigaciones mencionan un fenómeno cambio en las subjetividades y en los valores y creencias de la población chilena, tomando elementos individualistas y relevando el mérito como una forma de comprender las distribuciones de bienes y recursos, como también el orden social. Si bien hasta la fecha no se han recopilado investigaciones de corte cuantitativo que den cuenta sobre este fenómeno, Mijs () plantea el aumento de las creencias meritocráticas como una tendencia global, sobre todo en sociedades altamente desiguales. Considerando ambos fenómenos, es posible plantear la segunda hipótesis de que: 

> $H_2:$ Con el paso del tiempo, se fortalece la relación entre percepciones meritocráticas y atribuciones internas hacia la pobreza y la riqueza. 

