# Bibliografía {-}

Alesina, A., y Giuliano, P. (2009). Preferences for redistribution. IZA Discussion Papers 4056, Institute for the Study of Labor (IZA).
Alesina, A., y Glaeser, E. (2004). Fighting poverty in the US and Europe: A world of difference: A world. Rodolfo DeBenedetti lectures. UK: Oxford University Press.
Andersen, R., y Curtis, J. (2015). Social class, economic inequality, and the convergence of policy preferences: Evidence from 24 modern democracies. Revue canadienne de sociologie (Canadian Review of Sociology), 52(3), 266–288.
Araujo, K. (2017). Sujeto y neoliberalismo en Chile: rechazos y apegos. Nuevo Mundo Mundos Nuevos, February. https://doi.org/10.4000/nuevomundo.70649
Arcos, E., Canales, M., Muñoz, L., Toffoletto, M., Sánchez, X., y Vollrath, A. (2016). INVISIBILITY OF SOCIAL VULNERABILITY AND SOCIAL RIGHTS TO A COMPREHENSIVE HEALTH CARE IN CHILE. Texto y Contexto - Enfermagem, 25(4), e6150015. Epub December 12, 2016. https://doi.org/10.1590/0104-07072016006150015
Barozet, E. (2017). Serie sobre la clase media chilena (2): Ese gran miedo a resbalar. Publicado: 13.04.2017. https://www.ciperchile.cl/2017/04/13/66957/
Benabou, R., y Ok, E. A. (2001). Social mobility and the demand for redistribution: The POUM hypothesis? The Quarterly Journal of Economics, 116(2), 447–487
Bucca, Mauricio. 2016. “Merit and Blame in Unequal Societies: Explaining Latin Americans’ Beliefs about Wealth and Poverty”. Research in Social Stratification and Mobility 44: 98–112. DOI: https://doi.org/ 10.1016/j.rssm.2016.02.005
Bullock, H. E., Williams, W. R., y Limbert, W. M. (2003). Predicting support for welfare policies: The impact of attributions and beliefs about ine- quality. Journal of Poverty, 7, 35–56. doi:10.1300/ J134v07n03_03
Burchi, F., Rippin, N., Montenegro, C. (2018). From Income Poverty to Multidimensional Poverty: An International Comparison. Facultad de Economía y Negocios, Universidad de Chile. Departamento de economía. SDT 473
Godfrey, E. B., y Wolf, S. (2016). Developing critical consciousness or justifying the system? A qualitative analysis of attributions for poverty and wealth among low-income racial/ethnic minority and immigrant women. Cultural Diversity and Ethnic Minority Psychology, 22(1), 93–103. doi:10.1037/cdp0000048
Castillo, J. C., Iturra, J., & Meneses, F. (2020). Measuring Perceptions and Preferences for Meritocracy. 1–18.
Castillo, J. C., y Rivera-Gutiérrez, M. (2018). Dimensiones Comunes a las Atribuciones de Pobreza y Riqueza. Psykhe (Santiago), 27(2), 1–10. https://doi.org/10.7764/psykhe.27.2.1152
Castillo, J. C., Torres, A., Atria, J., y Maldonado, L. (2019). Meritocracy and economic inequality: Perceptions, preferences and implications. Revista Internacional de Sociologia, 77(1), 1–15. https://doi.org/10.3989/ris.2019.77.1.17.114
Cociña, M. (2013a). ¿Cree usted que la meritocracia es buena? Publicado el  05.06.2013. https://www.ciperchile.cl/2013/06/05/%C2%BFcree-usted-que-la-meritocracia-es-buena/
Cociña, M. (2013b). Cinco argumentos contra la Meritocracia. Publicado el 07.06.2013. https://www.ciperchile.cl/2013/06/07/cinco-argumentos-contra-la-meritocracia/
Cozzarelli, Catherine, Anna V. Wilkinson, y Michael J. Tagler. (2001). “Attitudes toward the Poor and Attributions for Poverty”. Journal of Social Issues 57 (2): 207–227. DOI: https://doi.org/10.1111/0022-4537.00209
Espinoza, V., Barozet, E. (2008). ¿De qué hablamos cuando decimos "clase media"? Perspectivas sobre el caso chileno. Expansiva UDP. Santiago de Chile.
Dixon, J., Levine, M., Reicher, S., y Durrheim, K. (2012). Beyond prejudice: Are negative evalu- ations the problem and is getting us to like one another more the solution? Behavioral and Brain Sciences, 35, 411-425. https://doi.org/10.1017/S0140525X11002214
Feagin, J. (1975). Subordinating the poor. New York, NY: Prentice Hall.
Flores, I., Sanhueza, C., Atria, J., y Mayer, R. (2019). Top Incomes in Chile: A Historical Perspective on Income Inequality, 1964–2017. Review of Income and Wealth, 01(0), 1–25. https://doi.org/10.1111/roiw.12441
Frei, R., Castillo, J. C., Herrera, R., y Suárez, J. I. (2020). ¿Fruto del esfuerzo? Los cambios en las atribuciones sobre pobreza y riqueza en chile entre 1996 y 2015. Latin American Research Review, 55(3), 477–495. https://doi.org/10.25222/larr.464
Ganzeboom, H. B., Treiman, D. J., y Ultee, W. C. (1991). Comparative Intergeneratio- nal Stratification Research: Three Generations And Beyond. Annual Review of Sociology, 17(1):277–302.
Gijsberts, M. (2002). The legitimation of income inequality in state-socialist and market societies? Acta Sociologica, 45(4), 269–285.
Gijsberts, M., & Ganzeboom, H. B. (2001). El apoyo a los principios distributivos. Una comparacin entre las sociedades socialistas y las sociedades de mercado (1987–1996). Poltica y Sociedad, 38.
Gissi-Barbieri, N., Polo Alvis, S. (2020). Social Incorporation of Colombian Migrants in Chile? Vulnerability and the Struggle for Recognition. Antipoda. Revista de Antropología y Arqueología, (38), 137-162. https://dx.doi.org/10.7440/antipoda38.2020.07
Goldthorpe, J. (2003). The myth of education-based meritocracy. why the theory isn’t wor- king. New Economy, 10(4):234–239.
Guzmán, V., Barozet, E., y  Méndez, M. (2017). Legitimación y crítica a la desigualdad: una aproximación pragmática. Convergencia. vol.24, n.73, pp.87-112. ISSN 2448-5799.
Heider, Fritz. 1958. The Psychology of Interpersonal Relations. Nueva York: John Wiley. DOI: https://doi.org/ 10.1037/10628-000
Hernández, J., Ramírez, H. (2020). Índice de Desarrollo Comunal. Chile 2020. Instituto Chileno de Estudios Municipales (ICHEM). Instituto de Estudios del Hábitat (IEH). Centro de Comunicación de las Ciencias. Universidad Autónoma de Chile. https://repositorio.uautonoma.cl/bitstream/handle/20.500.12728/6742/V11_digital_final.pdf?sequence=1yisAllowed=y
Hunt, Matthew O. 2004. “Race/Ethnicity and Beliefs about Wealth and Poverty”. Social Science Quarterly 85 (3): 827–853. DOI: https://doi.org/10.1111/j.0038-4941.2004.00247.x
Hunt, M. O. (1996). The individual, society, or both? A comparison of Black, Latino, and White beliefs about the causes of poverty. Social Forces, 75(1), 293–322.
Iturra, J. (2019). Sobre la relación entre el Estatus Social Subjetivo y la Percepción de Meritocracia: una aproximación empírica al caso de Chile. 
Kluegel, J. R., Smith, E. R. (1986). Social Institutions and Social Change. Beliefs About Inequality: Americans’ Views ofWhat Is and What Ought to be. Hawthorne, NY: Aldine de Gruyter.
Kreidl, Martin. 2000. “Perceptions of Poverty and Wealth in Western and Post-Communist Countries”. Social Justice Research 13 (2): 151–176. DOI: https://doi.org/10.1023/A:1007597807110
Kunovich, S., & Slomczynski, K. M. (2007). Systems of distribution and a sense of equity: A multilevel analysis of meritocratic atti- tudes in post-industrial societies. European Sociological Review, 23, 649–663. doi:10.1093/esr/jcm026
Lane, R. (1986). “Market Justice, Political Justice”. The Ameri- can Political Science Review 80(2): 383–402. https:// doi.org/10.2307/1958264
Lepianka, D. (2007) Are the Poor to be Blamed or Pitied? A Comparative Study of Popular Poverty Attributions in Europe. Tilburg: Tilburg University
Lepianka, D., van Oorschot, W. y Gelissen, J. (2009). Popular explanations of poverty: A critical discussion of empirical research. Journal of Social Policy, 38, 421-438. https://doi.org/10.1017/S0047279409003092
Littler, J. (2018). AGAINST MERITOCRACY Culture, power and myths of mobility. Routledge Taylor and Francis group. London and New York.
Lopez, R., Sturla, G. (2020). Hiper Fortunas y Súper Ricos: ¿Por qué un Impuesto al Patrimonio hace Sentido?. https://www.researchgate.net/publication/341735961_Hiper_Fortunas_y_Super_Ricos_Por_que_un_Impuesto_al_Patrimonio_hace_Sentido
 Mac-Clure, O., Barozet, E., Galleguillos, C. & Moya, C. (2015). La clase media clasifica a las personas en la sociedad: Resultados de una investigación empírica basada en juegos. Psicoperspectivas, 14(2), 4-15. Recuperado desde http://www.psicoperspectivas.cl doi:10.5027/PSICOPERSPECTIVAS-VOL14-ISSUE2-FULLTEXT-530
Madeira, A. F., Costa-Lopes, R., Dovidio, J. F., Freitas, G., & Mascarenhas, M. F. (2019). Primes and Consequences: A Systematic Review of Meritocracy in Intergroup Relations. Frontiers in Psychology, 10(September). https://doi.org/10.3389/fpsyg.2019.02007
Major, B., & Kaiser, C. R. (2017). Ideology and the maintenance of group inequality. Group Processes and Intergroup Relations, 20(5), 582–592. https://doi.org/10.1177/1368430217712051
Mijs, J. J. B., & Hoy, C. (2018). How Information About Economic Inequality Impacts Belief in Meritocracy : Evidence from a Randomized Survey Experiment in Australia, Indonesia, and Mexico. Social Problems.
Mijs, J. J. B., & Savage, M. (2020). Meritocracy, Elitism and Inequality. Political Quarterly, 91(2), 397–404. https://doi.org/10.1111/1467-923X.12828
Mijs, J. J. B. (2019). The paradox of inequality: income inequality and belief in meritocracy go hand in hand. Socio-Economic Review, 0(0), 1–29. https://doi.org/10.1093/ser/mwy051
Ministerio de Desarrollo Social (2017). PNUD 2017. Evolución de la pobreza 1990 - 2017: ¿Cómo ha cambiado Chile?. Gobierno de Chile. http://observatorio.ministeriodesarrollosocial.gob.cl/casen-multidimensional/casen/docs/InformeMDSF_Gobcl_Pobreza.pdf
Newman, B. J., Johnston, C. D. and Lown, P. L. (2015) ‘False Consciousness or Class Awareness? Local Income Inequality, Personal Economic Position, and Belief in American Meritocracy’, American Journal ofPolitical Science, 59, 326–340.
OECD (2018). A Broken Social Elevator? How to Promote Social Mobility. OECD, Paris.
Pereira, C., Vala, J. y Leyens, J.-Ph. (2009). From infra-humanization to discrimination: The mediation of symbolic threat needs egalitarian norms. Journal of Experimental Social Psychology, 45, 336-345. https://doi.org/10.1016/j.jesp.2008.10.010
Piketty, T. (1995). Social mobility and redistributive politics? The Quarterly Journal of Economics, 110(3), 551–584
PNUD (2017). Desiguales. Orígenes, cambios y desafíos de la brecha social en Chile. Santiago de Chile, Programa de las Naciones Unidas para el Desarrollo.
Robinson, R. V., & Bell, W. (1978). Equality, success, and social justice in England and the United States. American Sociological Review, 43(2), 125–143.
Roex, K. L. A., Huijts, T., y Sieben, I. (2019). Attitudes towards income inequality: ‘Winners’ versus ‘losers’ of the perceived meritocracy. Acta Sociologica (United Kingdom), 62(1), 47–63. https://doi.org/10.1177/0001699317748340
Sachweh, P. (2011). The moral economy of inequality: Popular views on income differentiation, poverty and wealth. Socio-Economic Review.
Sainz, M., Martínez, R., Sutton, R. M., Rodríguez-Bailón, R., y Moya, M. (2020). Less human, more to blame: Animalizing poor people increases blame and decreases support for wealth redistribution. Group Processes and Intergroup Relations, 23(4), 546–559. https://doi.org/10.1177/1368430219841135
Sainz, M., Martínez, R., Rodríguez-Bailón, R., y Moya, M. (2019). Where does the money come from? Humanizing high socioeconomic status groups undermines attitudes toward redistribution. Frontiers in Psychology, 10(MAR), 1–10. https://doi.org/10.3389/fpsyg.2019.00771
Schneider, S. M., y Castillo, J. C. (2015). Poverty Attributions and the Perceived Justice of Income Inequality: A Comparison of East and West Germany. Social Psychology Quarterly, 78(3), 263–282. https://doi.org/10.1177/0190272515589298
Schröder, M. (2017). Is Income Inequality Related to Tolerance for Inequality? Social Justice Research, 30(1), 23–47. https://doi.org/10.1007/s11211-016-0276-8
Seery, E. (2014) Working for the Many: Public Services Fight Inequality. Oxfam Briefing Paper, 182. Oxford, UK: Oxfam GB. Available at: https://policy-practice.oxfam.org.uk/publications/working- for-the-many-public-services-fight-inequality-314724 (accessed 7 August 2017).
Sen, A. (2000). Merit and Justice. Meritocracy and Economic Inequality, 5–16. https://doi.org/10.2307/j.ctv3hh4rk.5
World Economic Forum (2014) Global Risks 2014, Ninth Edition. Geneva, Switzerland: World Economic Forum. Available at: http://www3.weforum.org/docs/WEF_GlobalRisks_Report_2014.pdf (accessed 7 August 2017).
Young, M. (1962). The Rise of the Meritocracy. Baltimore: Penguin Books.
