---
title: "Analisis clases latentes 2019"
author: "Sebastián Cortinez"
date: "13-04-2021"
output: html_document
---


# Análisis clases latentes

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
# Para ingresar en poLCA se puede trabajar como int (numeric) o factor. Se deja código para trabajar en numerico, pero se procede a trabajarlas como
## At interna queda como 0 y At externa como 1

#proc_data_2019$Att_p1[proc_data_2019$Att_p1 == "atribucion interna"] <- 1
#proc_data_2019$Att_p1[proc_data_2019$Att_p1 == "atribucion externa"] <- 2

#proc_data_2019$Att_p2[proc_data_2019$Att_p2 == "atribucion interna"] <- 1
#proc_data_2019$Att_p2[proc_data_2019$Att_p2 == "atribucion externa"] <- 2

#proc_data_2019$Att_r1[proc_data_2019$Att_r1 == "atribucion interna"] <- 1
#proc_data_2019$Att_r1[proc_data_2019$Att_r1 == "atribucion externa"] <- 2

#proc_data_2019$Att_r2[proc_data_2019$Att_r2 == "atribucion interna"] <- 1
#proc_data_2019$Att_r2[proc_data_2019$Att_r2 == "atribucion externa"] <- 2

#proc_data_2019$Att_p1 <- sjlabelled::set_labels(proc_data_2019$Att_p1,
#            labels=c( "atribucion interna"=0,"atribucion externa"=1))
#proc_data_2019$Att_p2 <- sjlabelled::set_labels(proc_data_2019$Att_p2,
#            labels=c( "atribucion interna"=0,"atribucion externa"=1))
#proc_data_2019$Att_r1 <- sjlabelled::set_labels(proc_data_2019$Att_r1,
#            labels=c( "atribucion interna"=0,"atribucion externa"=1))
#proc_data_2019$Att_r2 <- sjlabelled::set_labels(proc_data_2019$Att_r2,
#            labels=c( "atribucion interna"=0,"atribucion externa"=1))


proc_data_2019$Att_p1<-as_factor(proc_data_2019$Att_p1)
proc_data_2019$Att_p2<-as_factor(proc_data_2019$Att_p2)
proc_data_2019$Att_r1<-as_factor(proc_data_2019$Att_r1)
proc_data_2019$Att_r2<-as_factor(proc_data_2019$Att_r2)

diccionario <- tibble::tibble(nombre = names(proc_data_2019), 
                    etiquetas = c("Per. merito esfuerzo","Per. merito intelig","Pref. merito responsabilidad","Pref. merito educacion","Pref. merito trabajo","Att. pobreza 1","Att. pobreza 2","Att. riqueza 1","Att. riqueza 2","sexo","edad","tramo ingresos","miembros hogar","ess","id. politica","nivel educacional","Per. merito ambicion","año","Att. i/e p. 1","Att. i/e p. 2","Att. i/e riq. 1","Att. i/e riq. 2"))

proc_data_2019 <- as.tibble(proc_data_2019)

proc_data_2019 %>% 
  dplyr::select(starts_with("Att_")) %>% 
  names() 
f <- cbind(Att_p1,Att_p2,Att_r1,Att_r2)~1
```


```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
proc_data_2019 %>% 
  dplyr::select(starts_with("Att_")) %>%  
  poLCA(f, ., nclass = 2, nrep = 4) -> LCA_2clases
```


```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
proc_data_2019 %>% 
  dplyr::select(starts_with("Att_")) -> bloque_att

# Para UNIX
#mclapply(1:9, function(x) {poLCA(f, bloque_att, nclass = x, nrep = 5)}) -> LCA_1a9

# Para Windows: 
lapply(1:9, function(x) {poLCA(f, bloque_att, nclass = x, nrep = 5)}) -> LCA_1a9


```

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
map_df(LCA_1a9, glance) %>% 
  kable(caption = "Comparación de modelos con 1 a nueve clases")
```


```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
map_df(LCA_1a9, glance) %>% 
  dplyr::select(-df, -df.residual, -chi.squared) %>% 
  mutate(modelo = as.character(1:nrow(.))) %>%
  gather(cantidad, valor, -modelo) %>% 
  ggplot(aes(x= modelo, y = valor, group = 1)) + 
    geom_line() + 
    geom_point() + 
    facet_wrap(~cantidad, scales = "free") +
    labs(title = "Comparación de modelos para el bloque p7", 
         subtitle = "La pendiente se aplana a partir de modelos con dos clases") + 
    theme_minimal()
```


```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}

etiquetas_item <- tibble(outcome = 1:length(levels(proc_data_2019$Att_p1)), 
                         etiqueta_item = c("Att interna","Att externa")
)
etiquetas_item$outcome<-as.factor(etiquetas_item$outcome)
#install.packages("colorspace")
library(colorspace)

LCA_1a9[[2]] %>% 
  tidy %>% 
  left_join(dplyr::rename(diccionario, variable = nombre)) %>% 
  left_join(etiquetas_item) %>% 
  mutate(etiquetas = str_remove(etiquetas, 
                                "Att"), 
         etiquetas = str_wrap(etiquetas, 30),
         etiqueta_item = factor(etiqueta_item, 
                                levels = c("Interna", "Externa")), 
         class = paste("Clase", class)) %>%
  ggplot(aes(x = etiquetas, fill = etiqueta_item, y = estimate)) + 
  geom_col() + 
  facet_wrap(~class, nrow = 1) + 
  scale_fill_viridis_d() + 
  theme_minimal() +
  theme(legend.position = "bottom") + 
  labs(fill = "Respuesta", 
       x = "Tipos de atribuciones", 
       y = "Probabilidad de respuesta por clase") + 
  coord_flip()

sessionInfo()
```


