---
title: "analisis clases latentes 2019"
author: "Sebastián Cortinez"
date: "4/7/2021"
output: html_document
---


```{r echo=FALSE, results='hide',warning=FALSE, message=FALSE}
options(scipen=999) # valores sin notación científica
#install.packages("pacman")
library(pacman)
#detach("package:memisc", unload = TRUE)
#install.packages("devtools")
# devtools::install_github("melff/memisc",subdir="pkg")
# devtools::install_github("AlineTalhouk/Amisc")
pacman::p_load(furniture,BiocManager,knitr,dplyr,foreign, sjmisc, car, sjlabelled, stargazer,kableExtra,corrplot,sessioninfo,readxl,pander,xtable, tidyverse, extrafont, ggplot2, forcats, ggpubr, naniar,haven, devtools,summarytools,webshot,pander,table1,gapminder,arsenal,magrittr,Gmisc,magick,htmltools,papeR,data.table,cowplot,gridExtra,reshape,poLCA,parallel,broom,Hmisc,sjPlot,nnet.texreg,MASS)
#webshot::install_phantomjs()

#  Cargar bbdd

load("../Input/Data_proc/2019/data_naomit2019.RData")
```

# Análisis clases latentes

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
f <- cbind(Att_p1,Att_p2,Att_r1,Att_r2)~1

f1 <- cbind(Att_p1,Att_p2)~1
f2 <- cbind(Att_r1,Att_r2)~1
```

## Análisis de tres clases con pob + riq

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
data_naomit2019 %>% 
  dplyr::select(starts_with("Att_")) %>%  
  poLCA(f, ., nclass = 3, nrep = 6, graphs = TRUE, maxiter = 100000) -> LCA_3clases_2019 # BIC = 6912.009; AIC = 6839.801

```


### Agregar columna con clases predichas

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
data_predclass_2019 <- cbind(data_naomit2019, "pred_atribuciones" = LCA_3clases_2019$predclass)
data_predclass_2019$pred_atribuciones<-as.factor(data_predclass_2019$pred_atribuciones)
data_predclass_2019$pred_atribuciones<-set_label(x=data_predclass_2019$pred_atribuciones, label = "Atribuciones 3 clases")
data_predclass_2019$pred_atribuciones <- car::recode(data_predclass_2019$pred_atribuciones, "1=3;2=1;3=2")
data_predclass_2019$pred_atribuciones <- sjlabelled::set_labels(data_predclass_2019$pred_atribuciones,
            labels=c( "Externa"=1,
                      "Ambivalente"=2,
                      "Interna"=3))
frq(data_predclass_2019$pred_atribuciones)
# Variable dependiente "ordinal" para regresión

data_predclass_2019 %>%
  mutate(pred_atribuciones_ord = ordered(pred_atribuciones)) -> data_predclass_2019



# Guardar BBDD con clases latentes

save(data_predclass_2019,file = "../Input/Data_proc/2019/data_predclass_2019.RData")
```










#(NO CORRER CÓDIGO)


## Análisis de dos clases con pob + riq (NO CORRER)

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
data_naomit2019 %>% 
  dplyr::select(starts_with("Att_")) %>%  
  poLCA(f, ., nclass = 2, nrep = 6, graphs = TRUE, maxiter = 5000) -> LCA_2clases # BIC = 6883.924; AIC = 6837.505
```

## Análisis de tres clases pobreza (NO CORRER)

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
frq(data_naomit2019$at_pobreza1)
data_naomit2019 %>% 
  dplyr::select(at_pobreza1,at_pobreza2) %>%  
  poLCA(xd, ., nclass = 3, nrep = 10, graphs = TRUE, maxiter = 100000) -> LCA_3clases # BIC = 
```

## Análisis de tres clases riqueza (NO CORRER)

```{r echo=FALSE, results='asis',warning=FALSE, message=FALSE}
data_naomit2019 %>% 
  dplyr::select(starts_with("Att_")) %>%  
  poLCA(f, ., nclass = 3, nrep = 6, graphs = TRUE, maxiter = 5000) -> LCA_3clases # BIC = 
```

